name: icollekt
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # firebase_messaging_platform_interface: 3.1.6
  # firebase_storage_platform_interface: 4.0.14
  # cloud_functions_platform_interface: 5.0.21
  # cloud_firestore_platform_interface: 5.4.13
  # firebase_auth_platform_interface: 6.1.11
  firebase_storage: 
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_staggered_grid_view: ^0.6.1
  emoji_picker_flutter: ^1.1.1
  permission_handler: 
  video_player: ^2.3.0
  helpers: ^1.1.4
  path_provider: ^2.0.8
  modal_bottom_sheet: ^2.0.0
  # video_editor: 
  firebase_messaging: 
  flutter_local_notifications: 
  path: ^1.7.0
  photo_view: ^0.13.0
  file_picker:
  flutter_native_splash: ^1.3.2
  fluttertoast: ^8.0.8
  filesize: ^2.0.1
  dio: ^4.0.4
  shared_value: ^2.1.0
  shared_preferences:
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.17
  firebase_auth:
  flutter_styled_toast: ^2.0.0
  flutter_cupertino_date_picker: 
  mailto: ^2.0.0 
  flutter_share: ^2.0.0
  firebase_dynamic_links: 
  dartz: ^0.10.1
  freezed: ^2.0.0
  cloud_firestore: 
  firebase_core:
  socket_io_client: ^1.0.2
  google_sign_in: ^5.2.4
  intl:
  webview_flutter: 
  lazy_load_scrollview: ^1.3.0
  flutter_widget_from_html: 
  flutter_inappwebview: ^5.4.3+7
  flutter_email_sender: ^5.0.2
  persistent_bottom_nav_bar: ^4.0.2
  multi_image_picker: ^4.7.14
  date_format: ^2.0.4
  flutter_riverpod: ^1.0.3
  flick_video_player: 
  visibility_detector: 
  flutter_svg: 
  flutter_swipe_action_cell: ^2.1.5
  image_picker:
  cached_network_image: ^3.2.0
  flutter_login_facebook: ^1.4.1  
  flutter_facebook_auth: ^4.1.1
  expandable: ^5.0.1
  like_button: ^2.0.4
  flutter_slidable: ^1.2.0
  pinch_zoom: ^1.0.0
  http: 
  country_pickers: ^2.0.0
  flutter_paypal: ^0.0.8
dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#FFFFFF"
  image: Assets/Images/Icollekt.png
flutter_icons:
  image_path: "Assets/Images/Icollekt.png"  
  # platform.
  android: true
  ios: true
  #web: false

  android_gravity: center
  ios_content_mode: center
  
  fullscreen: true
  
  

 
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/Images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
